export const SET_LOADING = 'setLoading'
export const FINISH_LOADING = 'finishLoading'
export const CLEAR_LOADING = 'clearLoading'
export const SET_MESSAGE = 'setMessage'
export const CLEAR_MESSAGE = 'clearMessage'
export const SET_ERROR = 'setError'
export const CLEAR_ERROR = 'clearError'
